$schema: "https://json-schema.org/draft/2020-12/schema"
type: object
required:
  - services
properties:
  services:
    type: object
    required:
      - backend-api
    properties:
      backend-api:
        type: object
        required:
          - image
          - ports
          - deploy
          - environment
        properties:
          image:
            type: string
          environment:
            type: array
            minItems: 1
            items:
              type: string
            contains:
              type: string
              pattern: "OPENROUTER_API_KEY"
          ports:
            type: array
            items:
              type: string
              enum: ["18020:8080"]
            minItems: 1
            maxItems: 1
          deploy:
            type: object
            required:
              - resources
            properties:
              resources:
                type: object
                required:
                  - limits
                properties:
                  limits:
                    type: object
                    required:
                      - cpus
                      - memory
                    properties:
                      cpus:
                        type: string
                        enum: ["0.5"]
                      memory:
                        type: string
                        enum: ["128MB"]
