services:
  backend-api:
    image: gandarez-ivr-service #latest
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    ports:
      - "18020:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128MB"
